on: [push]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: actions/setup-go@v5.1.0
        with:
          go-version: 1.23
      
      - name: Lint
        uses: golangci/golangci-lint-action@v6.1.1
        with:
          version: latest

      - name: Format check
        run: go fmt ./...

      - name: Static analysis
        run: go vet ./...

      - name: Test
        run: go test -coverprofile=coverage.out ./...

      - name: Upload test coverage report
        uses: codecov/codecov-action@v4.5.0
        with:
          file: ./coverage.out
          token: ${{ secrets.CODECOV_TOKEN }}
